### ISSUE TITLE
Exception in worker process:

### ISSUE THREAD

**Issue by NotII** [DankMemer/imgen#71]
Not sure if this is a issue with my setup or what but, I'm getting this error when starting with ./start.sh
```
[2020-05-25 14:41:02 +0000] [22576] [INFO] Worker exiting (pid: 22576)
[2020-05-25 14:41:02 +0000] [22575] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/usr/lib/python2.7/dist-packages/gunicorn/workers/ggevent.py", line 201, in init_process
    super(GeventWorker, self).init_process()
  File "/usr/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/usr/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/lib/python2.7/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/lib/python2.7/dist-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/usr/lib/python2.7/dist-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/lib/python2.7/dist-packages/gunicorn/util.py", line 366, in import_app
    __import__(module)
  File "/usr/local/lib/python2.7/dist-packages/gevent/builtins.py", line 96, in __import__
    result = _import(*args, **kwargs)
  File "/root/imgen/server.py", line 96
    return jsonify({"endpoints": [{'name': x, 'parameters': y.params, 'ratelimit': f'{y.rate}/{y.per}s'} for x, y in endpoints.items()]})
```
Config seems about right.

**Comment by FaZeBase** [comment]
Hey ! I also had the same issue and upgrading to Python 3 did the trick. You would need to reinstall Python (3) and imgen's dependencies

**Comment by GeoffreyWesthoff** [comment]
Make sure you are running at least Python 3.6 or newer and uninstall all instances of gunicorn on older versions, otherwise the gunicorn command will still point to the older version.   
  

  
  
  

  
  
>

**Comment by NotII** [comment]
Hi, I got it working but it seems like the server wont respond

**Comment by NotII** [comment]
Got it working eventually, When trying the oauth2 I'm getting Invalid Oauth2 redirect_uri 
My output url is 
https://discord.com/oauth2/authorize?response_type=code&client_id=720394043154235453&redirect_uri=<domain>%2Fcallback&scope=identify+email&state=hpp0r1IgFORhZHqQXi7EMdkcmAr2Sc

**Comment by mjshein** [comment]
I am getting this same error when starting using ./start.sh.
Though, I am using Python 3.6.8.
