### ISSUE TITLE
trouble starting imgen

### ISSUE THREAD

**Issue by leElvyn** [DankMemer/imgen#76]
I installed rethinkdb, cloned the repo and used `pip install requirements.txt`, but when running start.sh, I get this error 
`Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gunicorn/util.py", line
99, in load_class
    mod = importlib.import_module('.'.join(components))
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in
 import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_impo
rt
  File "<frozen importlib._bootstrap>", line 991, in _find_and_
load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_
load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlo
cked
  File "<frozen importlib._bootstrap_external>", line 783, in e
xec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with
_frames_removed
  File "/usr/lib/python3/dist-packages/gunicorn/workers/ggevent
.py", line 16, in <module>
    raise RuntimeError("gevent worker requires gevent 1.4 or hi
gher")
RuntimeError: gevent worker requires gevent 1.4 or higher
]`
Could you help me please ?
I'm running Ubuntu 20.04, and python 3.8.2

**Comment by NotII** [comment]
Try python 3.6

**Comment by Tweak4141** [comment]
You could use pip install gevent>1.4
